apiVersion: v1
kind: Service
metadata:
  name: coding-blog-service
  annotations:
    cloud.google.com/backend-config: '{"default": "coding-blog-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    component: coding-blog
