name: Auto-Approve Dependabot
on:
  pull_request:
    branches: [ main ] 
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only run this action on dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Wait for Build & Test
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for Analyze (csharp)
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Analyze (csharp)'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # This first step will fail if there's no dependabot metadata, so the PR approval will not occur.
      - name: Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # Approve the PR.
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Auto-merge the PR for patch and minor updates if all checks pass.
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

